server:
  port: 8090
  error:
    whitelabel:
      enabled: false

spring:
  messages:
    basename: messages/commonMessages,messages/itemMessages,messages/errors

  thymeleaf:
    cache: false
    enabled: true
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:XE
    username: refresh
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #show_sql : true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
